# Configuration for the selector
selector:
  # 9 slots in each row
  # double chest is 6
  # single chest is 3
  rows: 6
  # Should vaults that the player has no
  # permission be shown?
  show-locked: true
  # Item designs, how the items look etc.
  template:
    # Unlocked vault item
    unlocked:
      title: '&5Vault #%order'
      # Available placeholders:
      #    - %filled_slots (slots that are filled by items)
      #    - %total_slots (size of the inventory)
      #    - %free_slots (slots that are not filled by items)
      lore:
        - '&7%filled_slots/%total_slots slots filled.'
        - '&f '
        - '&7Click me to open!'
    # Locked vault item
    locked:
      title: '&5Vault &c(Locked)'
      lore:
        - '&7Unlock by donating at'
        - '&7store.example.com'

# Configuration for each vault
vault:
  # 9 slots in each row
  # double chest is 6
  # single chest is 3
  default-rows: 3
  # Items that players cannot put inside
  # their vaults.
  blacklist:
    enabled: false
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
    items:
      - BARRIER

# Auto save timer
auto-save:
  minutes: 15

# Data storage
storage:
  # Possible methods:
  #   - FLATFILE
  #   - MYSQL
  #   - MARIADB (preferred over MYSQL)
  method: FLATFILE

  # All the different settings for the storage methods.
  settings:
    flatfile:
      # Possible file formats:
      #   - YAML
      type: YAML
      # Where the data will be saved
      directory: 'data'
    mysql:
      # Address and port. Can specify as "host:port" or "host".
      # Default port for MySQL and MariaDB is 3306.
      address: 'localhost'

      # Database to create tables in
      database: 'minecraft'

      # Credentials
      user: 'minecraft'
      password: '123'

      # Connection properties, disable useSSL and verifyServerCertificate to
      # disable SSL connections.
      properties:
        cachePrepStmts: 'true'
        prepStmtCacheSize: '250'
        prepStmtCacheSqlLimit: '2048'
        useSSL: 'true'
        verifyServerCertificate: 'true'

      # Table names
      tables:
        vault: 'endervaults_vault'
        vault-metadata: 'endervaults_vault_metadata'
