# Configuration for the selector
selector:
  # 9 slots in each row
  # double chest is 6
  # single chest is 3
  rows: 6
  # Should pages be enabled?
  # If disabled, players won't be able to access
  # all their vaults from the selector.
  pages: true

# Configuration for each vault
vault:
  # 9 slots in each row
  # double chest is 6
  # single chest is 3
  default-rows: 3

# Auto save timer
auto-save:
  minutes: 15

# Data storage
storage:
  # Possible methods:
  #   - FLATFILE
  #   - MYSQL
  #   - MARIADB (preferred over MYSQL)
  method: FLATFILE

  # All the different settings for the storage methods.
  settings:
    flatfile:
      # Possible file formats:
      #   - YAML
      type: YAML
    mysql:
      # Address and port. Can specify as "host:port" or "host".
      # Default port for MySQL and MariaDB is 3306.
      address: 'localhost'

      # Database to create tables in
      database: 'minecraft'

      # Credentials
      user: 'minecraft'
      password: '123'

      # Connection properties, disable useSSL and verifyServerCertificate to
      # disable SSL connections.
      properties:
        cachePrepStmts: 'true'
        prepStmtCacheSize: '250'
        prepStmtCacheSqlLimit: '2048'
        useSSL: 'true'
        verifyServerCertificate: 'true'

      # Table names
      tables:
        vault: 'endervaults_vault'
        vault-metadata: 'endervaults_vault_metadata'
