# Configuration for the selector
selector:
  # 9 slots in each row
  # double chest is 6
  # single chest is 3
  rows: 6
  # Should pages be enabled?
  # If disabled, players won't be able to access
  # all their vaults from the selector.
  pages: true

# Configuration for each vault
vault:
  # 9 slots in each row
  # double chest is 6
  # single chest is 3
  default-rows: 3

# Data storage
storage:
  # FLATFILE
  type: FLATFILE
  #
  # Each type above has different settings below, please
  # check you have filled all the required fields.
  #
  # FLATFILE
  # settings:
  #   type: YAML
  #
  settings:
    type: YAML