name: EnderVaults
version: ${pluginVersion}
main: com.github.dig.endervaults.bukkit.EVBukkitPlugin
author: Digital
api-version: 1.13
commands:
  vault:
    description: Manage vaults
    aliases: [vaults, ev, endervault, endervaults, pv, playervault, playervaults]
  vaultreload:
    description: Reload endervault configuration files
    aliases: [pvreload, evadmin]
  vaultadmin:
    description: Access players vaults as an admin
    aliases: [pvadmin, evadmin]