name: EnderVaults
version: 1.0.0
main: com.github.dig.endervaults.bukkit.EVBukkitPlugin
author: Digital
commands:
  vault:
    description: Manage vaults
    aliases: [vaults, ev, endervault, endervaults, pv, playervault, playervaults]
  vaultreload:
    description: Reload endervault configuration files
    aliases: [pvreload]