name: EnderVaults
version: 1.0
main: com.github.dig.endervaults.bukkit.EVBukkitPlugin
author: Digital
commands:
  vault:
    description: Manage vaults
    aliases: [vaults, pv, playervault, playervaults]